src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="image")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *     max="255",
     *     maxMessage="Le nom de votre image est trop long...",
     * )
     */
    private $alt;

    private $file;

    private $tempFilename;

    public function getId()
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
        return 'upload/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../public/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username", message = "Ce pseudo n'est pas disponible")
 * @UniqueEntity("email", message = "Cette adresse mail n'est pas disponible")
 */
class User implements UserInterface, \Serializable
{

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Moto", cascade={"persist"}, inversedBy="users")
     * @ORM\JoinTable(name="user_moto")
     */
    private $motos;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     * @Assert\Length(min="5", minMessage="Votre pseudo doit être composé d'au moins 5 caractères")
     * @Assert\Regex(pattern="/^[a-zA-Z0-9]+$/i", message = "Votre pseudo ne peut pas contenir de caractères spéciaux")
     */
    private $username;

    /**
     * @ORM\Column(name = "email", type="string", length=60, unique = true)
     * @Assert\Email(message = "Veuillez renseigner une adresse mail avec un format correct (ex : Doctorbike@gmail.com)")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=60)
     * @Assert\Length(min="8", minMessage="Votre mot de passe  doit être composé d'au moins 8 caractères")
     * @Assert\Length(max="60", maxMessage="Votre mot de passe  ne peut excéder les 60 caractères")
     * @Assert\Regex(pattern="/^[a-zA-Z0-9]+$/i", match = false,  message = "Votre mot de passe doit contenir au moins une majuscule, un nombre et un caractère spécial")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vos mots de passe ne sont pas identiques")
     */
    private $confirm_password;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\LessThan("Today UTC", message="La date ne peut être supérieur à aujourd'hui")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    public $confirmationToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $confirmedAt;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $resetAt;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Scenario", mappedBy="user", orphanRemoval=true)
     */
    private $scenarios;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Historique", mappedBy="user", orphanRemoval=true)
     */
    private $historiques;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Moto", cascade={"persist", "remove"})
     */
    private $motoActive;


    public function __construct()
    {
        $this->scenarios = new ArrayCollection();
        $this->historiques = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmPassword(): ?string
    {
        return $this->confirm_password;
    }

    public function setConfirmPassword(string $confirm_password): self
    {
        $this->confirm_password = $confirm_password;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }


    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }

    public function getConfirmedAt(): ?\DateTimeInterface
    {
        return $this->confirmedAt;
    }

    public function setConfirmedAt(?\DateTimeInterface $confirmedAt): self
    {
        $this->confirmedAt = $confirmedAt;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getResetAt(): ?\DateTimeInterface
    {
        return $this->resetAt;
    }

    public function setResetAt(?\DateTimeInterface $resetAt): self
    {
        $this->resetAt = $resetAt;

        return $this;
    }

    public function eraseCredentials()
    {
    }

    public function getSalt()
    {
        return null;
    }

    public function getRoles()
    {
        $roles = $this->roles;

        return $roles;
    }

    public function setRoles(array $roles)
    {
        $this->roles = $roles;
    }

    /**
     * @return Collection|Moto[]
     */
    public function getMotos(): Collection
    {
        return $this->motos;
    }

    public function addMoto(Moto $moto): self
    {
        if (!$this->motos->contains($moto)) {
            $this->motos[] = $moto;
        }

        return $this;
    }

    public function removeMoto(Moto $moto): self
    {
        if ($this->motos->contains($moto)) {
            $this->motos->removeElement($moto);
        }

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }

    /**
     * @return Collection|Scenario[]
     */
    public function getScenarios(): Collection
    {
        return $this->scenarios;
    }

    public function addScenario(Scenario $scenario): self
    {
        if (!$this->scenarios->contains($scenario)) {
            $this->scenarios[] = $scenario;
            $scenario->setUser($this);
        }

        return $this;
    }

    public function removeScenario(Scenario $scenario): self
    {
        if ($this->scenarios->contains($scenario)) {
            $this->scenarios->removeElement($scenario);
            // set the owning side to null (unless already changed)
            if ($scenario->getUser() === $this) {
                $scenario->setUser(null);
            }
        }

        return $this;
    }

    public function checkIfUserMotoExists($moto)
    {
        $motoIfExist = null;

        foreach ($this->getMotos() as $element) {
            if ($element == $moto) {
                $motoIfExist = $element;
                break;
            }

        }

        return $motoIfExist;
    }

    /**
     * @return Collection|Historique[]
     */
    public function getHistoriques(): Collection
    {
        return $this->historiques;
    }

    public function addHistorique(Historique $historique): self
    {
        if (!$this->historiques->contains($historique)) {
            $this->historiques[] = $historique;
            $historique->setUser($this);
        }

        return $this;
    }

    public function removeHistorique(Historique $historique): self
    {
        if ($this->historiques->contains($historique)) {
            $this->historiques->removeElement($historique);
            // set the owning side to null (unless already changed)
            if ($historique->getUser() === $this) {
                $historique->setUser(null);
            }
        }

        return $this;
    }

    public function getMotoActive(): ?Moto
    {
        return $this->motoActive;
    }

    public function setMotoActive(?Moto $motoActive): self
    {
        $this->motoActive = $motoActive;

        return $this;
    }

    // Méthode permettant de récupérer la valeur (0 ou 1) d'un vote pour une solution donnée
    public function getVoteForSolution($idSolution)
    {
        $vote = null;

        // On parcours les votes de l'utilisateur
        foreach ($this->historiques as $element)
        {
            // Si la solution du vote actuel représente la solution en paramètre
            // Et que la moto du vote représente la moto active de l'utilisateur
            if ($element->getSolution()->getId() == $idSolution && $element->getMoto()->getId() == $this->motoActive->getId())
            {
                $vote = $element;
            }
        }

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer cet utilisateur ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/user/gestionDesUsers.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} text-center">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    <div class="block push">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="jumbotron jumbotron-fluid">
                         <h1>Liste de tous les utilisateurs</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <h3>Rechercher un utilisateur <span style="font-weight: bold; color: dodgerblue; font-size: 25px">({{ pagination.getTotalItemCount }} utilisateur(s) au total)</span></h3>
                    <form>
                        <div class="input-group mb-3">
                            <input type="text"
                                   name="q"
                                   class="form-control"
                                   placeholder="Vous pouvez rechercher un utilisateur par son email ou son pseudo"
                            >
                            <div class="input-group-append">
                                <button type="submit"
                                        class="btn btn-primary fa fa-search">
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <table class="table table-hover table-responsive-sm">
                    <thead>
                    <tr>
                        <th style="vertical-align: middle;">Avatar</th>
                        <th style="vertical-align: middle;">Pseudo</th>
                        <th style="vertical-align: middle;">Mail</th>
                        <th style="vertical-align: middle;">Rôle</th>
                        <th style="vertical-align: middle;">Scénario créé</th>
                        <th style="vertical-align: middle;">Incrit depuis</th>
                        <th style="vertical-align: middle;"></th>
                        <th style="vertical-align: middle;"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in pagination %}
                        <tr>
                            {% if user.image %}
                            <td>
                                <img
                                        src="{{ asset(user.image.webPath) }}"
                                        alt="{{ user.image.alt }}"
                                        width="60px"
                                        height="60px"
                                        class="img-responsive img-circle"
                                />
                            </td>
                            {% else %}
                                <td>Aucun avatar</td>
                            {% endif %}

                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>

                            {% for role in user.roles %}
                                <td>{{ role }}</td>
                            {% endfor %}

                            <td>{{ user.scenarios.count }}</td>

                            <td>{{ user.confirmedAt|date("d/m/Y") }}</td>
                            <td>
                                <a href="{{ path('gestionDesUsersUpdate', {'id': user.id}) }}"><button class="btn btn-warning">Modifier l'utilisateur</button></a>
                            </td>
                            <td>
                                <a href="{{ path('user_show', {'id': user.id}) }}"><button class="btn btn-info">Voir l'utilisateur</button></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="12">Aucun enregistrement pour le moment</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/user/gestionDesUsersUpdate.html.twig
{% extends 'base.html.twig' %}

{% form_theme formAdminUpdateUser 'bootstrap_4_layout.html.twig' %}

{% block body %}

    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} text-center">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    <div class="container">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="jumbotron jumbotron-fluid">
                        <h1>Gestion des informations de {{ user.username }}</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card bg-dark text-primary">
                        <div class="card-header" style="text-align: center">
                            <h4>Modification des données de l'utilisateur</h4>
                        </div>
                            <div class="card-body">
                                {{ form_start(formAdminUpdateUser) }}

                                {{ form_errors(formAdminUpdateUser) }}

                                {{ form_row(formAdminUpdateUser.username, {'attr': {'placeholder': "Exemple : RascarKapack"}}) }}

                                {{ form_row(formAdminUpdateUser.email, {'attr': {'placeholder': "Exemple : Rascar@gmail.com"}}) }}

                                {{ form_row(formAdminUpdateUser.roles) }}

                                {{ form_rest(formAdminUpdateUser) }}

                                <button type="submit" class="btn btn-success btn-block">
                                    Enregistrer les modifications
                                </button>

                                {{ form_end( formAdminUpdateUser )}}

                                <br>
                                <a style="text-underline: none" href="{{ path('gestionDesUsers') }}"><button class="btn btn-info">Revenir à la liste des utilisateurs</button></a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/inscription.html.twig
{% extends 'base.html.twig' %}

{% form_theme formUser 'bootstrap_4_layout.html.twig' %}


{% block body %}

    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} text-center">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    <div class="block push">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="jumbotron jumbotron-fluid">
                        <h1>Inscription</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card bg-dark text-primary">
                        <div class="card-header" style="text-align: center">
                            <h4>Veuillez remplir ce formulaire pour vous inscrire</h4>
                        </div>
                        <div class="card-body">
                            {{ form_start(formUser) }}

                            {{ form_errors(formUser) }}

                            {{ form_row(formUser.username, {'attr': {'placeholder': "Exemple : RascarKapack"}}) }}

                            {{ form_row(formUser.email, {'attr': {'placeholder': "Exemple : Rascar@gmail.com"}}) }}

                            {{ form_row(formUser.password) }}

                            {{ form_row(formUser.confirm_password) }}

                            {{ form_row(formUser.dateDeNaissance) }}

                            <button type="submit" class="btn btn-success btn-block">
                                S'inscrire
                            </button>

                            {{ form_rest(formUser) }}

                            {{ form_end(formUser) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="block push">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="jumbotron jumbotron-fluid">
                        <h1>Utilisateur sélectionné :</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center" style="margin-bottom: 25px;">
                    {% if user.image %}
                        <img
                                src="{{ asset(user.image.webPath) }}"
                                alt="{{ user.image.alt }}"
                                width="150px"
                                height="150px"
                                class="img-responsive img-circle"
                        />
                    {% else %}
                        <td>Aucun avatar</td>
                    {% endif %}

                </div>

                <table class="table table-hover table-responsive-sm">
                    <thead>
                    <tr>
                        <th>Pseudo</th>
                        <th>Email</th>
                        <th>Inscrit depuis</th>
                        <th>Nombre de scénarios créés</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.confirmedAt|date("d/m/Y") }}</td>
                        <td>{{ user.scenarios.count }}</td>
                        <td>{{ include('user/_delete_form.html.twig') }}</td>
                    </tr>
                    </tbody>
                </table>
                <a href="{{ path('gestionDesUsers') }}" class="btn btn-info">Revenir à la liste des utilisateurs</a>
            </div>
        </div>
    </div>


{% endblock %}